### ISSUE TITLE
Are comments on attributes from the wrong perspective?

### ISSUE THREAD

**Issue by idg10** [idg10/azure-sdk-for-net#10]
Comments such as this:

```
/// <summary>
/// Indicates that the <see cref="Field"/> generated by <see cref="FieldBuilder"/> for
/// the target property should have its <see cref="Field.Analyzer"/> property set to the
/// specified analyzer.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class AnalyzerAttribute : Attribute
...
```

are accurate, and for someone migrating from the existing 'bring your own fields' approach to the reflection model, they might be helpful because they describe things in terms of what you would otherwise have done by hand.

But I'm wondering whether these are unhelpful comments to anyone coming to the SDK from scratch. When I started using the SDK I went looking for a reflection-based index build, and would have used it if it existed. And in that context, the current comments would be less helpful. So I'm wondering if I should rewrite all the comments on these attributes based on the assumption that whoever's reading them regards the reflection-based approach as the normal one.

E,g,, this should read something more like "Indicates that the field should use the specified analyzer."

**Comment by bitsforthought** [comment]
Yes, I think it would be helpful to make the documentation more task-oriented and conceptual. Feel free to borrow text from the property definitions of the `Field` class.
