### ISSUE TITLE
Add attributes for all Field options

### ISSUE THREAD

**Issue by idg10** [idg10/azure-sdk-for-net#3]
Currently we have `IsSearchable`. As @brjohnstmsft says in https://github.com/idg10/azure-sdk-for-net/commit/960a03e4b30107b2c6eaea3809ca8cd560057c88#commitcomment-19294124 we also need "`IsFilterable`, `IsFacetable`, `IsSortable`, `Analyzer`/`SearchAnalyzer`/`IndexAnalyzer`, etc."

Add all these, and work out what "etc." entails and do that too.

**Comment by idg10** [comment]
I think this is the list of boolean properties that need attributes:
- `IsSearchable`
- `IsFilterable`
- `IsSortable`
- `IsFacetable`
- `IsRetrievable` (note: true by default)

and then there are the three analyzer properties:
- `Analyzer`
- `SearchAnalyzer`
- `IndexAnalyzer`

So as far as I can tell, the full contents of 'etc' are just `IsRetrievable`. And for that I think we need a negative because the default is true, so that would be `IsNotRetrievableAttribute`.

**Comment by idg10** [comment]
Hmm... Turns out the analyzer ones are tricky, because analyzers are identified by static members of `AnalyzerName`, and you can't refer to a static property (or any property) in an attribute.

**Comment by bitsforthought** [comment]
Can we rename `IsNotRetrievableAttribute` to `IsHiddenAttribute`?

Regarding `AnalyzerName`, that is tricky. I'll reply [here](https://github.com/idg10/azure-sdk-for-net/commit/960a03e4b30107b2c6eaea3809ca8cd560057c88#commitcomment-19300107) for better continuity.

**Comment by idg10** [comment]
Regarding Analyzers @brjohnstmsft said this at https://github.com/idg10/azure-sdk-for-net/commit/960a03e4b30107b2c6eaea3809ca8cd560057c88#commitcomment-19311876 : 

In order to keep the names of the strings and AnalyzerName instances aligned, we could introduce another level of indirection:

```
public class AnalyzerName
{
    ...
    public static readonly AnalyzerName EnMicrosoft = new AnalyzerName(AsString.EnMicrosoft);
    ...
    public static class AsString
    {
        public const string EnMicrosoft = "en.microsoft";
    }
}
```

I'm not sure if this compiles... If need be, we can always define the strings as private constants at the top of the AnalyzerName class and then reference each string in both the outer and nested classes.

The usage of this would look like [Analyzer(AnalyzerName.AsString.EnMicrosoft)].

What do you think?

**Comment by idg10** [comment]
It does compile, and it seems reasonable, given the constraints.
