### ISSUE TITLE
Rename IsNotRetrievableAttribute to IsRetrievableAttribute

### ISSUE THREAD

**Issue by idg10** [idg10/azure-sdk-for-net#9]
@brjohnstmsft didn't like my name. 😃 https://github.com/idg10/azure-sdk-for-net/issues/3#issuecomment-251841095

**Comment by idg10** [comment]
While `IsNotRetrievableAttribute` is slightly clunky, I'm not sure about `IsHiddenAttribute` because it seems a bit vague to me. Hidden from whom or what? From the search engine? (No, but that's not obvious from the name.) And there's also a disconnect between the attribute name and the corresponding `Field` property, which is inconsistent with all the other similar attributes. That's alone will cause discoverability problems, so I think we need 'Retrievable' in there.

How about `[IsRetrievable(false)]`? That way the naming is completely consistent with all the others, and it chimes well with the code you'd write if you weren't using the attribute (`field.IsRetrievable = false;`) It's not perfect - it would make this the only attribute that takes an argument, and it also enables people to write the `[IsRetrievable(true)]` which would have no effect.

**Comment by bitsforthought** [comment]
I take your point about consistency, and taking a Boolean parameter is a good way to make it explicit. `[IsRetrievable(false)]` it is.
